### ISSUE TITLE
Fail of Uploading In Local Storage Mode 

### ISSUE THREAD

**Issue by zbouziane** [catalogueglobal/datatools-server#11]
With use_s3_storage set to false:
```
17/04/20 12:14:10.621 [Thread-14] WARN  com.conveyal.gtfs.BaseGTFSCache - Feed tampere-20170420T121408+02-f6a79e00-b150-4725-b385-712826a46351 not found locally
java.lang.NullPointerException
	at com.conveyal.datatools.manager.models.FeedVersion.getGtfsFeed(FeedVersion.java:182)
	at com.conveyal.datatools.editor.jobs.ProcessGtfsSnapshotMerge.run(ProcessGtfsSnapshotMerge.java:130)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by landonreed** [comment]
This code path has been significantly altered and no longer produces this NPE.
